### ISSUE TITLE
Does global `udp::socket` store need to be implemented as an Asio service

### ISSUE THREAD

**Issue by inetic** [inetic/asio-utp#4]
Continuing @vinniefalco's [comment](https://github.com/inetic/asio-utp/issues/2#issuecomment-451318177) from issue #2:

> Globals like this are a problem:
> [asio-utp/src/context.cpp](https://github.com/inetic/asio-utp/blob/994f50f1d56d0f12ab97cc75f73f305ddd66fadf/src/context.cpp#L41)
> 
> Line 41 in [994f50f](/inetic/asio-utp/commit/994f50f1d56d0f12ab97cc75f73f305ddd66fadf)
> 
>  static std::map<endpoint_type, shared_ptr<context>> loops; 
> Globals associated with an `io_context` need to be installed using `asio::use_service`
> https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/use_service/overload1.html
> 
> Your `context` is essentially a service, it just needs to be installed correctly.

**Comment by inetic** [comment]
I'm doing some studying on Asio's `services`, I _think_ I understand their purpose but I may not be 100% there yet. I found [this SO post](https://stackoverflow.com/questions/23887056/trying-to-understand-boost-asio-custom-service-implementation) and have also looked into [this logger service example](https://github.com/boostorg/asio/tree/develop/example/cpp03/services).

First, I am [aware](https://github.com/inetic/asio-utp#todo) that `asio-utp` isn't thread safe at the moment. And also that one of the benefits of using Asio's `services` is thread safety. But from what I've gathered, these `services` are primarily for when there are blocking or long running tasks that need to be run in separate threads to emulate asynchronicity.

`asio-utp` doesn't have any blocking code, nor long running tasks. It internally uses `asio::udp::sockets` to which access does need to be made thread safe, but which already have their service inside Asio and thus are async.

Thus it feels to me that using Asio's service here would be bringing too big of a gun to a problem which (I think) can be solved with few mutexes: one around that global `std::map` and one inside each `utp::context`.

But again, I may be missing something, so feedback is very welcome.

**Comment by vinniefalco** [comment]
Asio's "service" is meant for exactly one thing: To store variables specific to the io_context. It has nothing to do with thread safety. Say, for example, that I wanted to use a cryptographically secure random number generator in Beast websockets. I want one such generator **per io_context**. Where to store the instance? We can't use a function-scope static variable, that is only one per program. And it won't be destroyed when the `io_context` is destroyed.

Instead, we can ask the `io_context` to create and store the instance for us by creating a "service." This is accomplished by calling `use_service` on the `io_context`. That is what services are for. As you can see, they are quite open-ended. You can essentially do whatever you want. It is a way of adding behavior or data to the `io_context` at run-time, without intruding on the public-facing API.

Your use-case is actually the perfect example of what the I/O context service API should be used for. Currently you have a function-scoped static variable which applies to **all** UTP sockets. Instead, you should have a per-`io_context` associated variable which stores data on all UTP sockets **using that I/O context**. The difference here is that when the I/O context is destroyed, your service will also be notified and get destroyed, and you can make everything work cleanly.

With the service approach, if you have two different `io_context` objects using UTP sockets, then each `io_context` will have its own instance of the UTP service, and one will not affect the other. Each `io_context` can be independently operated and destroyed. This is how your implementation should work, as it is the cleanest.

**Comment by inetic** [comment]
> Asio's "service" is meant for exactly one thing: To store variables specific to the io_context.
> It is a way of adding behavior or data to the io_context at run-time, without intruding on the public-facing API.

This is a very informative explanation, thanks.

Must say, I wasn't convinced by the "`utp::context` per `io_context`" argument. That is, while there is a 1-to-1 correspondence between a UDP socket and a `utp::context`, there isn't such correspondence between a `utp::context` and `io_context`. In fact, one `io_context` can support multiple `utp::contexts`. It's also not the case that there could be two sockets in two different `io_contexts` bound to the same port.

While it would be an option to have an Asios's service hold multiple `utp::contexts`, having them stored all in one function-scoped static `std::map` would have been my preference were there no other arguments simply because it's less code.

> The difference here is that when the I/O context is destroyed, your service will also be notified and get destroyed, and you can make everything work cleanly.

I thought I had this covered: each `utp::context` has a [counter] counting how many `socket_impl` instances are using it. When the [last `socket_impl` stops using it] (i.e. when it's closed), it calls [utp::context::stop] to shut it down. Then, when the last async action finishes, the `utp::context` gets destroyed and removes itself from the function-scoped static variable map (I just realized I forgot to implement this last removing part, but that's easily fixable).

What I forgot to account for was the case where the user destroys all `utp::sockets` and then also the ~~`utp::context`~~ `asio::io_context` without letting it run out of jobs. In this scenario there could still be `socket_impls` hanging around waiting for their async jobs to finish (`socket_impl` and `utp::context` do some FIN packet sending after the `utp::socket` is closed).

_This_ seems like something that I can only resolve by using Asio's services. Unfortunately, I don't see clearly how without introducing _another_ `asio::io_context` together with a new worker thread that would `run` it. These two would then execute the work of the `asio::udp::socket` inside the `utp::context`.

Do you agree that creating the new worker thread and the `io_context` is the only way to approach that problem? If it's indeed the case, it feels like applications which would normally only run one `io_context::run()` until it finishes (where this problem wouldn't exist) need to needlessly suffer context switches (plus whatever is the cost of pushing and popping to/from `io_context`'s job queue).

The speed concern is also expressed in [that SO question at the end](https://stackoverflow.com/questions/23887056/trying-to-understand-boost-asio-custom-service-implementation), but the answer (although very good) doesn't seem to address it.

[counter]: https://github.com/inetic/asio-utp/blob/master/src/context.hpp#L64
[last `socket_impl` stops using it]: https://github.com/inetic/asio-utp/blob/master/src/context.cpp#L192
[utp::context::stop]: https://github.com/inetic/asio-utp/blob/master/src/context.cpp#L208

**Comment by vinniefalco** [comment]
What if the caller simply stops the I/O context by calling `io_context::stop` and then invokes the destructor (`~io_context`)? In this case, none of the UTP socket operations run to completion and you are left with dangling resources.

**Comment by inetic** [comment]
Yes, that's exactly the problem I tried to describe in the "What I forgot to account for ..." paragraph above.

To be clear, I am now convinced that I do need to make use of Asio's service. Where I'm at in my thinking process right now is to figure out how to best approach the dangling resources problem.

Some posts (like the [the answer in the above mentioned SO post](https://stackoverflow.com/a/23897448/273348) or [this other one](https://stackoverflow.com/questions/52146630/is-there-a-way-to-explicitly-destroy-all-handlers-pending-on-a-given-boostasio)) seem to suggest the best way is to create a new worker thread where I'd run my `asio-utp` related IO and then `join` that thread somewhere in `my_service::shutdown_service()` or `my_service::destroy(impl_type&)` once all work has finished.

I have a feeling it can be done without the worker thread, but not 100% sure yet.

Sorry for if this is an incoherent brain dump, I'm thinking out loud.

**Comment by vinniefalco** [comment]
I think if the io_context is destroyed then you should not try to block or wait, pending the completion/acknowledgement of sending FIN or whatever else. Would that be ok?

**Comment by inetic** [comment]
What I meant was to _not_ block to finish the FIN handshake, but to close all the sockets, cancel all the timers and then wait for them to execute whatever handlers they have attached. That should be quick enough.

I remember some 5 years ago if I did not let all pending actions finish and destroyed the `io_service` I was getting crashes. I'm not 100% sure whether that was due to a bug in Asio or I was doing something silly. But since then I always exit my apps by closing all IO objects and then waiting for their async actions to get executed.

Perhaps that is no longer necessary and I can simply let the handlers not-execute prior to `io_context` destruction. That's what I meant above by

> I have a feeling it can be done without the worker thread, but not 100% sure yet.

**Comment by vinniefalco** [comment]
> Perhaps that is no longer necessary 

I don't think it is necessary, your crash was caused by something else.

**Comment by inetic** [comment]
As of commit [83557309](https://github.com/inetic/asio-utp/commit/83557309496fac2cc5722de7019cecb1087533b6), `::asio_utp::context`s are stored in class `asio_utp::context_service` derived from `asio::io_context::service`.

@vinniefalco, thanks again for your input.
